# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitFollower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FollowerId', models.IntegerField()),
            ],
            options={
                'db_table': 'TwitFollower',
            },
        ),
        migrations.CreateModel(
            name='TwitPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.TextField(blank=True, null=True)),
                ('PostDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'TwitPost',
            },
        ),
        migrations.CreateModel(
            name='TwitUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TwitUser',
            },
        ),
        migrations.AddField(
            model_name='twitpost',
            name='TwitUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TwitUser'),
        ),
        migrations.AddField(
            model_name='twitfollower',
            name='TwitUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TwitUser'),
        ),
    ]
